"use strict";

import { QueryInterface } from "sequelize";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface: QueryInterface) {
    await queryInterface.bulkInsert("roles", [
      {
        role: "Doctor",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
          "clinic:create",
          "clinic:edit",
          "clinic:delete",
          "clinic:view",
          "disease:create",
          "disease:edit",
          "disease:delete",
          "disease:view",
          "division:create",
          "division:edit",
          "division:delete",
          "division:view",
          "household:create",
          "household:edit",
          "household:delete",
          "household:view",
          "resident:create",
          "resident:edit",
          "resident:delete",
          "resident:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Nurse",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
          "clinic:create",
          "clinic:edit",
          "clinic:delete",
          "clinic:view",
          "disease:create",
          "disease:edit",
          "disease:delete",
          "disease:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Surgeon",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
          "clinic:create",
          "clinic:edit",
          "clinic:delete",
          "clinic:view",
          "disease:create",
          "disease:edit",
          "disease:delete",
          "disease:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Pediatrician",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
          "clinic:create",
          "clinic:edit",
          "clinic:delete",
          "clinic:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Radiologist",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
          "clinic:create",
          "clinic:edit",
          "clinic:delete",
          "clinic:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Lab Technician",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Pharmacist",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Matron",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Medical Officer",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
          "role:create",
          "role:edit",
          "role:delete",
          "role:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Emergency Responder",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Physiotherapist",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Biomedical Engineer",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Receptionist",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Ward Attendant",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Infection Control Nurse",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Anesthesiologist",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        role: "Nutritionist",
        permission: JSON.stringify([
          "user:create",
          "user:edit",
          "user:delete",
          "user:view",
        ]),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.bulkDelete("roles", {
      role: [
        "Doctor",
        "Nurse",
        "Surgeon",
        "Pediatrician",
        "Radiologist",
        "Lab Technician",
        "Pharmacist",
        "Matron",
        "Medical Officer",
        "Emergency Responder",
        "Physiotherapist",
        "Biomedical Engineer",
        "Receptionist",
        "Ward Attendant",
        "Infection Control Nurse",
        "Anesthesiologist",
        "Nutritionist",
      ],
    });
  },
};
