"use strict";

import { QueryInterface } from "sequelize";

/** Seed file for residents */
export default {
  async up(queryInterface: QueryInterface): Promise<void> {
    try {
      await queryInterface.bulkInsert("residents", [
        {
          firstName: "Kasun",
          lastName: "Perera",
          nic: "912345678V",
          email: "kasun.perera@example.com",
          password: "hashedpassword1",
          birthday: new Date("1990-03-15"),
          bloodGroup: "A+",
          gender: "Male",
          bloodPressure: "120/80",
          heartRate: "72",
          address: "123 Main St, Colombo",
          contactNumber: "0771234567",
          divisionId: 1,
          maritalState: "Single",
          educationLevel: "Graduate",
          addicted: JSON.stringify(["None"]),
          alergies: JSON.stringify(["Pollen"]),
          chronicalDesease: JSON.stringify(["None"]),
          height: 175,
          weight: 68,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nimali",
          lastName: "Fernando",
          nic: "925678912V",
          email: "nimali.fernando@example.com",
          password: "hashedpassword2",
          birthday: new Date("1992-07-10"),
          bloodGroup: "B+",
          gender: "Female",
          bloodPressure: "110/70",
          heartRate: "75",
          address: "456 Galle Rd, Galle",
          contactNumber: "0712345678",
          divisionId: 2,
          maritalState: "Married",
          educationLevel: "Diploma",
          addicted: JSON.stringify(["Coffee"]),
          alergies: JSON.stringify([]),
          chronicalDesease: JSON.stringify([]),
          height: 160,
          weight: 55,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Tharindu",
          lastName: "Jayasinghe",
          nic: "900987654V",
          email: "tharindu.j@example.com",
          password: "hashedpassword3",
          birthday: new Date("1990-01-20"),
          bloodGroup: "O+",
          gender: "Male",
          bloodPressure: "130/85",
          heartRate: "78",
          address: "No. 45, Kandy Rd, Kandy",
          contactNumber: "0755554444",
          divisionId: 3,
          maritalState: "Single",
          educationLevel: "Masters",
          addicted: JSON.stringify([]),
          alergies: JSON.stringify(["Dust"]),
          chronicalDesease: JSON.stringify(["Asthma"]),
          height: 172,
          weight: 70,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Sajini",
          lastName: "Wickramasinghe",
          nic: "931234567V",
          email: "sajini.wick@example.com",
          password: "hashedpassword4",
          birthday: new Date("1993-09-05"),
          bloodGroup: "AB+",
          gender: "Female",
          bloodPressure: "115/75",
          heartRate: "80",
          address: "Negombo Rd, Negombo",
          contactNumber: "0765432109",
          divisionId: 4,
          maritalState: "Single",
          educationLevel: "Graduate",
          addicted: JSON.stringify(["Tea"]),
          alergies: JSON.stringify([]),
          chronicalDesease: JSON.stringify([]),
          height: 158,
          weight: 52,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Dilan",
          lastName: "Senanayake",
          nic: "881234567V",
          email: "dilan.sena@example.com",
          password: "hashedpassword5",
          birthday: new Date("1988-11-11"),
          bloodGroup: "A-",
          gender: "Male",
          bloodPressure: "140/90",
          heartRate: "82",
          address: "Panadura, Western",
          contactNumber: "0777777777",
          divisionId: 5,
          maritalState: "Married",
          educationLevel: "High School",
          addicted: JSON.stringify(["Smoking"]),
          alergies: JSON.stringify(["Peanuts"]),
          chronicalDesease: JSON.stringify(["Hypertension"]),
          height: 178,
          weight: 80,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Harshini",
          lastName: "Rathnayake",
          nic: "941234567V",
          email: "harshini.rath@example.com",
          password: "hashedpassword6",
          birthday: new Date("1994-05-23"),
          bloodGroup: "B-",
          gender: "Female",
          bloodPressure: "118/78",
          heartRate: "76",
          address: "Kurunegala Rd, Kurunegala",
          contactNumber: "0786543210",
          divisionId: 6,
          maritalState: "Single",
          educationLevel: "Graduate",
          addicted: JSON.stringify([]),
          alergies: JSON.stringify(["Seafood"]),
          chronicalDesease: JSON.stringify([]),
          height: 162,
          weight: 58,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ruwan",
          lastName: "Gunasekara",
          nic: "861234567V",
          email: "ruwan.g@example.com",
          password: "hashedpassword7",
          birthday: new Date("1986-06-30"),
          bloodGroup: "O-",
          gender: "Male",
          bloodPressure: "125/80",
          heartRate: "70",
          address: "Anuradhapura, North Central",
          contactNumber: "0723456789",
          divisionId: 7,
          maritalState: "Married",
          educationLevel: "Diploma",
          addicted: JSON.stringify(["Alcohol"]),
          alergies: JSON.stringify([]),
          chronicalDesease: JSON.stringify(["Diabetes"]),
          height: 180,
          weight: 85,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Iresha",
          lastName: "De Silva",
          nic: "951234567V",
          email: "iresha.ds@example.com",
          password: "hashedpassword8",
          birthday: new Date("1995-12-01"),
          bloodGroup: "AB-",
          gender: "Female",
          bloodPressure: "110/65",
          heartRate: "74",
          address: "Matara, Southern Province",
          contactNumber: "0745678901",
          divisionId: 8,
          maritalState: "Single",
          educationLevel: "Undergraduate",
          addicted: JSON.stringify(["Energy Drinks"]),
          alergies: JSON.stringify(["Milk"]),
          chronicalDesease: JSON.stringify([]),
          height: 155,
          weight: 50,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Amal",
          lastName: "Wijesinghe",
          nic: "871234567V",
          email: "amal.wij@example.com",
          password: "hashedpassword9",
          birthday: new Date("1987-08-08"),
          bloodGroup: "A+",
          gender: "Male",
          bloodPressure: "135/88",
          heartRate: "77",
          address: "Badulla, Uva Province",
          contactNumber: "0734567890",
          divisionId: 9,
          maritalState: "Divorced",
          educationLevel: "High School",
          addicted: JSON.stringify(["Cigarettes"]),
          alergies: JSON.stringify([]),
          chronicalDesease: JSON.stringify([]),
          height: 173,
          weight: 75,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Chamari",
          lastName: "Rajapaksha",
          nic: "961234567V",
          email: "chamari.raj@example.com",
          password: "hashedpassword10",
          birthday: new Date("1996-02-14"),
          bloodGroup: "B+",
          gender: "Female",
          bloodPressure: "112/70",
          heartRate: "72",
          address: "Ratnapura, Sabaragamuwa",
          contactNumber: "0701234567",
          divisionId: 10,
          maritalState: "Married",
          educationLevel: "Graduate",
          addicted: JSON.stringify([]),
          alergies: JSON.stringify(["Gluten"]),
          chronicalDesease: JSON.stringify([]),
          height: 160,
          weight: 54,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
    } catch (error) {
      console.error("Error seeding residents:", error);
    }
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    try {
      await queryInterface.bulkDelete(
        "residents",
        {
          email: [
            "kasun.perera@example.com",
            "nimali.fernando@example.com",
            "tharindu.j@example.com",
            "sajini.wick@example.com",
            "dilan.sena@example.com",
            "harshini.rath@example.com",
            "ruwan.g@example.com",
            "iresha.ds@example.com",
            "amal.wij@example.com",
            "chamari.raj@example.com",
          ],
        },
        {}
      );
    } catch (error) {
      console.log(error);
    }
  },
};
